using System.Globalization;

namespace VelaShell.Plugin.DockerPanel;

/// <summary>
/// 插件自带的文案表(理由同 Telnet / S3 插件:领域词汇随插件走,
/// 宿主不替一个自己不认识的领域背词典)。只带英文与简体中文两套,其余语言回落英文。
/// </summary>
/// <param name="locale">宿主当前语言(如 <c>zh-Hans</c>、<c>en</c>)。</param>
public sealed class Loc(string locale)
{
    private readonly bool _chinese = locale.StartsWith("zh", StringComparison.OrdinalIgnoreCase);

    /// <summary>取一条文案;未收录的键原样返回(方便一眼看出漏了哪条)。</summary>
    /// <param name="key">文案键。</param>
    /// <returns>文案。</returns>
    public string this[string key] =>
        (_chinese ? Chinese : English).TryGetValue(key, out var value) ? value : key;

    /// <summary>取一条带占位符的文案并格式化。</summary>
    /// <param name="key">文案键。</param>
    /// <param name="args">占位参数。</param>
    /// <returns>格式化后的文案。</returns>
    public string Format(string key, params object?[] args) =>
        string.Format(CultureInfo.CurrentCulture, this[key], args);

    private static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
        // ── 命令面板 / 面板标题 ──────────────────────────────────────────
        ["Command_Open"] = "Docker: Open Docker Panel",
        ["Command_Category"] = "Docker",
        ["Panel_Title"] = "Docker",
        ["Panel_TitleWithHost"] = "Docker · {0}",

        // ── 头部 ────────────────────────────────────────────────────────
        ["Header_Session"] = "Session",
        ["Header_NoSessions"] = "No connected SSH session",
        ["Header_Refresh"] = "Refresh",
        ["Header_AutoRefresh"] = "Auto",
        ["Header_AutoOff"] = "off",
        ["Header_Seconds"] = "{0}s",
        ["Header_Settings"] = "Settings",
        ["Header_Sudo"] = "Run docker with sudo",
        ["Header_SudoHint"] = "Uses `sudo -n` (never prompts). Only works if this account has a password-free sudo rule for docker.",
        ["Header_DockerHost"] = "DOCKER_HOST",
        ["Header_DockerHostHint"] = "Leave empty to use the remote default. Example: unix:///var/run/docker.sock",
        ["Header_DockerContext"] = "DOCKER_CONTEXT",
        ["Header_DockerContextHint"] = "Leave empty to use the remote default docker context.",
        ["Header_Counts"] = "{0}/{1} containers · {2} images · {3} volumes",
        ["Header_Apply"] = "Apply",
        ["Header_Close"] = "Close",

        // ── 引擎状态 ────────────────────────────────────────────────────
        ["Engine_Probing"] = "Probing docker…",
        ["Engine_Ready"] = "docker {0}",
        ["Engine_NoSession"] = "Pick a connected SSH session to start.",
        ["Engine_Missing"] = "docker was not found on this host (is it installed and on PATH?).",
        ["Engine_Daemon"] = "The docker daemon is not reachable — it may be stopped.",
        ["Engine_Denied"] = "Permission denied on the docker socket. Add this account to the `docker` group, or turn on \"Run docker with sudo\".",
        ["Engine_SudoPassword"] = "sudo asked for a password. `sudo -n` cannot answer it — configure a NOPASSWD rule for docker, or turn sudo back off.",
        ["Engine_Other"] = "docker could not be reached: {0}",
        ["Engine_ComposeMissing"] = "compose not available",
        ["Engine_Compose"] = "compose {0}",
        ["Engine_Live"] = "live",
        ["Engine_LiveHint"] = "Connected to the docker event stream — the panel updates itself; the timer below is only a fallback.",

        // ── 页签 ────────────────────────────────────────────────────────
        ["Tab_Containers"] = "Containers",
        ["Tab_Images"] = "Images",
        ["Tab_Volumes"] = "Volumes",
        ["Tab_Networks"] = "Networks",
        ["Tab_Compose"] = "Compose",
        ["Tab_System"] = "System",

        // ── 通用 ────────────────────────────────────────────────────────
        ["Common_Filter"] = "Filter…",
        ["Common_ShowAll"] = "All",
        ["Common_ShowAllHint"] = "Include stopped containers",
        ["Common_ShowAllImagesHint"] = "Include intermediate layers",
        ["Common_WithSize"] = "Size",
        ["Common_WithSizeHint"] = "Also compute the writable layer size (noticeably slower with many containers)",
        ["Common_Empty"] = "Nothing here.",
        ["Common_Loading"] = "Loading…",
        ["Common_Cancel"] = "Cancel",
        ["Common_Confirm"] = "Confirm",
        ["Common_Copy"] = "Copy",
        ["Common_CopyId"] = "Copy id",
        ["Common_Inspect"] = "Inspect",
        ["Common_Delete"] = "Delete",
        ["Common_Selected"] = "{0} selected",
        ["Common_Run"] = "Run",
        ["Common_Yes"] = "Yes",
        ["Common_No"] = "No",

        // ── 容器 ────────────────────────────────────────────────────────
        ["Container_Start"] = "Start",
        ["Container_Stop"] = "Stop",
        ["Container_Restart"] = "Restart",
        ["Container_Pause"] = "Pause",
        ["Container_Unpause"] = "Unpause",
        ["Container_Kill"] = "Kill",
        ["Container_Remove"] = "Remove",
        ["Container_Rename"] = "Rename",
        ["Container_Terminal"] = "Shell",
        ["Container_TerminalHint"] = "Types `docker exec -it … sh` into this session's terminal tab (needs your approval).",
        ["Container_RestartPolicy"] = "Restart policy",
        ["Col_Name"] = "NAME",
        ["Col_Image"] = "IMAGE",
        ["Col_State"] = "STATE",
        ["Col_Status"] = "STATUS",
        ["Col_Ports"] = "PORTS",
        ["Col_Created"] = "CREATED",
        ["Col_Cpu"] = "CPU",
        ["Col_Mem"] = "MEM",
        ["Col_Project"] = "PROJECT",

        // ── 镜像 ────────────────────────────────────────────────────────
        ["Image_Pull"] = "Pull",
        ["Image_Push"] = "Push",
        ["Image_Tag"] = "Tag",
        ["Image_History"] = "History",
        ["Image_Remove"] = "Remove",
        ["Image_RunFrom"] = "Run…",
        ["Image_PruneDangling"] = "Prune dangling",
        ["Col_Repository"] = "REPOSITORY",
        ["Col_Tag"] = "TAG",
        ["Col_ImageId"] = "IMAGE ID",
        ["Col_Size"] = "SIZE",

        // ── 卷 ──────────────────────────────────────────────────────────
        ["Volume_Create"] = "Create",
        ["Volume_Remove"] = "Remove",
        ["Volume_Prune"] = "Prune unused",
        ["Col_VolumeName"] = "VOLUME",
        ["Col_Driver"] = "DRIVER",
        ["Col_Mountpoint"] = "MOUNTPOINT",
        ["Col_Scope"] = "SCOPE",

        // ── 网络 ────────────────────────────────────────────────────────
        ["Network_Create"] = "Create",
        ["Network_Remove"] = "Remove",
        ["Network_Prune"] = "Prune unused",
        ["Network_Connect"] = "Connect…",
        ["Network_Disconnect"] = "Disconnect…",
        ["Col_NetworkName"] = "NETWORK",
        ["Col_Internal"] = "INTERNAL",
        ["Col_IPv6"] = "IPV6",

        // ── Compose ─────────────────────────────────────────────────────
        ["Compose_Up"] = "Up -d",
        ["Compose_Down"] = "Down",
        ["Compose_Restart"] = "Restart",
        ["Compose_Stop"] = "Stop",
        ["Compose_Start"] = "Start",
        ["Compose_Pull"] = "Pull",
        ["Compose_Build"] = "Build",
        ["Compose_Ps"] = "Services",
        ["Compose_Logs"] = "Logs",
        ["Compose_Config"] = "Validate",
        ["Compose_Edit"] = "Edit file",
        ["Compose_AddFile"] = "Open file…",
        ["Compose_Unavailable"] = "Neither `docker compose` nor `docker-compose` is available on this host.",
        ["Compose_Hint"] = "`compose ls` only knows projects that have been started at least once. Use \"Open file…\" for anything else.",
        ["Col_ProjectStatus"] = "STATUS",
        ["Col_ConfigFiles"] = "COMPOSE FILE",

        // ── 系统 ────────────────────────────────────────────────────────
        ["System_Version"] = "Version",
        ["System_Info"] = "Info",
        ["System_DiskUsage"] = "Disk usage",
        ["System_Prune"] = "Reclaim space",
        ["Prune_Containers"] = "Stopped containers",
        ["Prune_Images"] = "Dangling images",
        ["Prune_ImagesAll"] = "All unused images",
        ["Prune_Volumes"] = "Unused volumes",
        ["Prune_Networks"] = "Unused networks",
        ["Prune_BuildCache"] = "Build cache",
        ["Prune_All"] = "Everything",
        ["Prune_AllWithVolumes"] = "Everything + volumes",

        // ── 抽屉 ────────────────────────────────────────────────────────
        ["Drawer_Details"] = "Inspect",
        ["Drawer_Logs"] = "Logs",
        ["Drawer_Top"] = "Processes",
        ["Drawer_Diff"] = "Changes",
        ["Drawer_Ports"] = "Ports",
        ["Drawer_History"] = "History",
        ["Drawer_Services"] = "Services",
        ["Drawer_Config"] = "Config",
        ["Drawer_File"] = "File",
        ["Drawer_Output"] = "Command log",
        ["Drawer_Empty"] = "Select a row above.",
        ["Drawer_Save"] = "Save",
        ["Drawer_Reload"] = "Reload",
        ["Drawer_Wrap"] = "Wrap",
        ["Drawer_Follow"] = "Follow",
        ["Drawer_FollowHint"] = "Re-fetches new log lines on the auto-refresh interval (docker logs -f cannot be used over a one-shot exec channel).",
        ["Drawer_Timestamps"] = "Timestamps",
        ["Drawer_Tail"] = "Lines",
        ["Drawer_Clear"] = "Clear",
        ["Drawer_CopyAll"] = "Copy all",
        ["Drawer_Hide"] = "Hide",
        ["Drawer_LogFilter"] = "Contains…",

        // ── 表单 ────────────────────────────────────────────────────────
        ["Form_Preview"] = "Will run",
        ["Form_Submit"] = "Run",
        ["Form_Pull_Title"] = "Pull an image",
        ["Form_Pull_Image"] = "Image reference",
        ["Form_Pull_AllTags"] = "All tags (-a)",
        ["Form_Pull_Platform"] = "Platform",
        ["Form_Run_Title"] = "Run a container from {0}",
        ["Form_Run_Name"] = "Container name",
        ["Form_Run_Ports"] = "Port mappings (one per line)",
        ["Form_Run_Volumes"] = "Volume mounts (one per line)",
        ["Form_Run_Env"] = "Environment (one KEY=value per line)",
        ["Form_Run_Network"] = "Network",
        ["Form_Run_Restart"] = "Restart policy",
        ["Form_Run_Detach"] = "Detached (-d)",
        ["Form_Run_Rm"] = "Remove on exit (--rm)",
        ["Form_Run_Extra"] = "Extra arguments",
        ["Form_Run_ExtraHint"] = "Spliced into the command line as typed — exactly as powerful as typing it in the terminal.",
        ["Form_Run_Command"] = "Command override",
        ["Form_Rename_Title"] = "Rename {0}",
        ["Form_Rename_Name"] = "New name",
        ["Form_Tag_Title"] = "Tag {0}",
        ["Form_Tag_Target"] = "New reference",
        ["Form_Volume_Title"] = "Create a volume",
        ["Form_Volume_Name"] = "Name",
        ["Form_Volume_Driver"] = "Driver",
        ["Form_Volume_Options"] = "Driver options (one key=value per line)",
        ["Form_Volume_Labels"] = "Labels (one key=value per line)",
        ["Form_Network_Title"] = "Create a network",
        ["Form_Network_Name"] = "Name",
        ["Form_Network_Driver"] = "Driver",
        ["Form_Network_Subnet"] = "Subnet",
        ["Form_Network_Gateway"] = "Gateway",
        ["Form_Network_Internal"] = "Internal (no outbound access)",
        ["Form_Network_IPv6"] = "Enable IPv6",
        ["Form_Connect_Title"] = "Connect a container to {0}",
        ["Form_Connect_Container"] = "Container",
        ["Form_Connect_Alias"] = "Network alias",
        ["Form_Disconnect_Title"] = "Disconnect a container from {0}",
        ["Form_Policy_Title"] = "Restart policy",
        ["Form_Policy_Value"] = "Policy",
        ["Form_Exec_Title"] = "Open a shell in {0}",
        ["Form_Exec_Shell"] = "Shell",
        ["Form_Exec_User"] = "User",
        ["Form_Exec_Workdir"] = "Working directory",
        ["Form_ComposeFile_Title"] = "Open a compose file",
        ["Form_ComposeFile_Path"] = "Remote path",
        ["Form_ComposeFile_Project"] = "Project name",
        ["Form_ComposeFile_ProjectHint"] = "Leave empty to let compose derive it from the directory name.",

        // ── 确认 ────────────────────────────────────────────────────────
        ["Confirm_Type"] = "Type {0} to confirm",
        ["Confirm_RemoveContainers"] = "Remove {0} container(s)?",
        ["Confirm_RemoveContainersBody"] = "The container and its writable layer go away. Named volumes survive; anonymous ones only if you tick \"with volumes\".",
        ["Confirm_RemoveContainersVolumes"] = "with anonymous volumes (-v)",
        ["Confirm_Kill"] = "Kill {0} container(s)?",
        ["Confirm_KillBody"] = "SIGKILL — the process gets no chance to flush buffers or close connections. Prefer Stop unless it is wedged.",
        ["Confirm_RemoveImages"] = "Remove {0} image(s)?",
        ["Confirm_RemoveImagesBody"] = "Anything not cached elsewhere has to be pulled again.",
        ["Confirm_RemoveVolumes"] = "Delete {0} volume(s)?",
        ["Confirm_RemoveVolumesBody"] = "This deletes the data inside them. There is no undo and no recycle bin.",
        ["Confirm_RemoveNetworks"] = "Remove {0} network(s)?",
        ["Confirm_RemoveNetworksBody"] = "Containers still attached will lose that network.",
        ["Confirm_ComposeDown"] = "Bring down {0}?",
        ["Confirm_ComposeDownBody"] = "Stops and removes the project's containers and networks.",
        ["Confirm_ComposeDownVolumes"] = "also delete the project's volumes (-v)",
        ["Confirm_Prune"] = "Reclaim space: {0}?",
        ["Confirm_PruneBody"] = "Everything unused in that category is deleted right away.",
        ["Confirm_PruneVolumesBody"] = "Unused volumes are deleted — including data you may still want. This is the one prune that loses data.",
        ["Confirm_SaveComposeFile"] = "Overwrite {0}?",
        ["Confirm_SaveComposeFileBody"] = "The remote file is replaced with what is in the editor. Take a backup first if it is not in version control.",

        // ── 状态栏 ──────────────────────────────────────────────────────
        ["Status_Ready"] = "Ready.",
        ["Status_Working"] = "{0}…",
        ["Status_Refreshed"] = "Refreshed at {0}.",
        ["Status_Done"] = "{0}: done.",
        ["Status_Failed"] = "{0} failed: {1}",
        ["Status_Batch"] = "{0}: {1} ok, {2} failed — {3}",
        ["Status_BatchOk"] = "{0}: {1} ok.",
        ["Status_NoSelection"] = "Select at least one row first.",
        ["Status_NoSession"] = "Pick a connected SSH session first.",
        ["Status_Copied"] = "Copied.",
        ["Status_TerminalSent"] = "Sent to the terminal tab.",
        ["Status_TerminalDenied"] = "You declined writing to the terminal, so nothing was sent.",
        ["Status_Saved"] = "Saved {0}.",
        ["Status_FileRead"] = "Loaded {0}.",
        ["Status_Cancelled"] = "Cancelled.",
        ["Status_EngineUnavailable"] = "docker is not usable on this session yet."
    };

    private static readonly Dictionary<string, string> Chinese = new(StringComparer.Ordinal)
    {
        ["Command_Open"] = "Docker: 打开 Docker 管理面板",
        ["Command_Category"] = "Docker",
        ["Panel_Title"] = "Docker",
        ["Panel_TitleWithHost"] = "Docker · {0}",

        ["Header_Session"] = "会话",
        ["Header_NoSessions"] = "没有已连接的 SSH 会话",
        ["Header_Refresh"] = "刷新",
        ["Header_AutoRefresh"] = "自动",
        ["Header_AutoOff"] = "关",
        ["Header_Seconds"] = "{0} 秒",
        ["Header_Settings"] = "设置",
        ["Header_Sudo"] = "以 sudo 执行 docker",
        ["Header_SudoHint"] = "用的是 `sudo -n`(绝不弹口令提示)。只有当这个账号对 docker 配了免密 sudo 规则时才有效。",
        ["Header_DockerHost"] = "DOCKER_HOST",
        ["Header_DockerHostHint"] = "留空即用远端默认值。例:unix:///var/run/docker.sock",
        ["Header_DockerContext"] = "DOCKER_CONTEXT",
        ["Header_DockerContextHint"] = "留空即用远端默认的 docker context。",
        ["Header_Counts"] = "容器 {0}/{1} · 镜像 {2} · 卷 {3}",
        ["Header_Apply"] = "应用",
        ["Header_Close"] = "收起",

        ["Engine_Probing"] = "正在探测 docker…",
        ["Engine_Ready"] = "docker {0}",
        ["Engine_NoSession"] = "选一条已连接的 SSH 会话开始。",
        ["Engine_Missing"] = "这台机器上找不到 docker(装了吗?在 PATH 里吗?)。",
        ["Engine_Daemon"] = "连不上 docker daemon —— 它可能没启动。",
        ["Engine_Denied"] = "没有 docker socket 的权限。把这个账号加进 `docker` 组,或者打开「以 sudo 执行 docker」。",
        ["Engine_SudoPassword"] = "sudo 要口令,而 `sudo -n` 不会去答它 —— 给 docker 配一条 NOPASSWD 规则,或者把 sudo 关掉。",
        ["Engine_Other"] = "docker 不可用:{0}",
        ["Engine_ComposeMissing"] = "无 compose",
        ["Engine_Compose"] = "compose {0}",
        ["Engine_Live"] = "实时",
        ["Engine_LiveHint"] = "已接上 docker 事件流 —— 面板会自己更新;右边的定时刷新只是退路。",

        ["Tab_Containers"] = "容器",
        ["Tab_Images"] = "镜像",
        ["Tab_Volumes"] = "卷",
        ["Tab_Networks"] = "网络",
        ["Tab_Compose"] = "Compose",
        ["Tab_System"] = "系统",

        ["Common_Filter"] = "过滤…",
        ["Common_ShowAll"] = "全部",
        ["Common_ShowAllHint"] = "连已停止的容器一起列",
        ["Common_ShowAllImagesHint"] = "连中间层一起列",
        ["Common_WithSize"] = "大小",
        ["Common_WithSizeHint"] = "顺带算出可写层大小(容器一多会明显变慢)",
        ["Common_Empty"] = "这里什么都没有。",
        ["Common_Loading"] = "加载中…",
        ["Common_Cancel"] = "取消",
        ["Common_Confirm"] = "确认",
        ["Common_Copy"] = "复制",
        ["Common_CopyId"] = "复制 id",
        ["Common_Inspect"] = "详情",
        ["Common_Delete"] = "删除",
        ["Common_Selected"] = "已选 {0} 项",
        ["Common_Run"] = "执行",
        ["Common_Yes"] = "是",
        ["Common_No"] = "否",

        ["Container_Start"] = "启动",
        ["Container_Stop"] = "停止",
        ["Container_Restart"] = "重启",
        ["Container_Pause"] = "暂停",
        ["Container_Unpause"] = "恢复",
        ["Container_Kill"] = "强杀",
        ["Container_Remove"] = "删除",
        ["Container_Rename"] = "重命名",
        ["Container_Terminal"] = "进容器",
        ["Container_TerminalHint"] = "把 `docker exec -it … sh` 敲进这条会话的终端标签(需要你授权)。",
        ["Container_RestartPolicy"] = "重启策略",
        ["Col_Name"] = "名称",
        ["Col_Image"] = "镜像",
        ["Col_State"] = "状态",
        ["Col_Status"] = "描述",
        ["Col_Ports"] = "端口",
        ["Col_Created"] = "创建",
        ["Col_Cpu"] = "CPU",
        ["Col_Mem"] = "内存",
        ["Col_Project"] = "项目",

        ["Image_Pull"] = "拉取",
        ["Image_Push"] = "推送",
        ["Image_Tag"] = "打标签",
        ["Image_History"] = "历史",
        ["Image_Remove"] = "删除",
        ["Image_RunFrom"] = "运行…",
        ["Image_PruneDangling"] = "清理悬空镜像",
        ["Col_Repository"] = "仓库",
        ["Col_Tag"] = "标签",
        ["Col_ImageId"] = "镜像 ID",
        ["Col_Size"] = "大小",

        ["Volume_Create"] = "新建",
        ["Volume_Remove"] = "删除",
        ["Volume_Prune"] = "清理未使用",
        ["Col_VolumeName"] = "卷名",
        ["Col_Driver"] = "驱动",
        ["Col_Mountpoint"] = "挂载点",
        ["Col_Scope"] = "作用域",

        ["Network_Create"] = "新建",
        ["Network_Remove"] = "删除",
        ["Network_Prune"] = "清理未使用",
        ["Network_Connect"] = "接入容器…",
        ["Network_Disconnect"] = "摘除容器…",
        ["Col_NetworkName"] = "网络名",
        ["Col_Internal"] = "内部",
        ["Col_IPv6"] = "IPv6",

        ["Compose_Up"] = "启动 (up -d)",
        ["Compose_Down"] = "销毁 (down)",
        ["Compose_Restart"] = "重启",
        ["Compose_Stop"] = "停止",
        ["Compose_Start"] = "启动",
        ["Compose_Pull"] = "拉取镜像",
        ["Compose_Build"] = "构建",
        ["Compose_Ps"] = "服务列表",
        ["Compose_Logs"] = "日志",
        ["Compose_Config"] = "校验配置",
        ["Compose_Edit"] = "编辑文件",
        ["Compose_AddFile"] = "打开文件…",
        ["Compose_Unavailable"] = "这台机器上既没有 `docker compose` 也没有 `docker-compose`。",
        ["Compose_Hint"] = "`compose ls` 只认得起过至少一次的项目。其它的用「打开文件…」。",
        ["Col_ProjectStatus"] = "状态",
        ["Col_ConfigFiles"] = "COMPOSE 文件",

        ["System_Version"] = "版本",
        ["System_Info"] = "信息",
        ["System_DiskUsage"] = "磁盘占用",
        ["System_Prune"] = "回收空间",
        ["Prune_Containers"] = "已停止的容器",
        ["Prune_Images"] = "悬空镜像",
        ["Prune_ImagesAll"] = "全部未使用镜像",
        ["Prune_Volumes"] = "未使用的卷",
        ["Prune_Networks"] = "未使用的网络",
        ["Prune_BuildCache"] = "构建缓存",
        ["Prune_All"] = "以上全部",
        ["Prune_AllWithVolumes"] = "以上全部 + 卷",

        ["Drawer_Details"] = "详情",
        ["Drawer_Logs"] = "日志",
        ["Drawer_Top"] = "进程",
        ["Drawer_Diff"] = "文件变更",
        ["Drawer_Ports"] = "端口",
        ["Drawer_History"] = "构建历史",
        ["Drawer_Services"] = "服务",
        ["Drawer_Config"] = "配置",
        ["Drawer_File"] = "文件",
        ["Drawer_Output"] = "执行记录",
        ["Drawer_Empty"] = "先在上面选一行。",
        ["Drawer_Save"] = "保存",
        ["Drawer_Reload"] = "重新读取",
        ["Drawer_Wrap"] = "自动换行",
        ["Drawer_Follow"] = "跟随",
        ["Drawer_FollowHint"] = "按自动刷新的间隔增量拉取新日志(一次性 exec 通道用不了 docker logs -f)。",
        ["Drawer_Timestamps"] = "时间戳",
        ["Drawer_Tail"] = "行数",
        ["Drawer_Clear"] = "清空",
        ["Drawer_CopyAll"] = "复制全部",
        ["Drawer_Hide"] = "收起",
        ["Drawer_LogFilter"] = "包含…",

        ["Form_Preview"] = "将执行",
        ["Form_Submit"] = "执行",
        ["Form_Pull_Title"] = "拉取镜像",
        ["Form_Pull_Image"] = "镜像引用",
        ["Form_Pull_AllTags"] = "拉全部标签 (-a)",
        ["Form_Pull_Platform"] = "平台",
        ["Form_Run_Title"] = "用 {0} 运行一个容器",
        ["Form_Run_Name"] = "容器名",
        ["Form_Run_Ports"] = "端口映射(一行一条)",
        ["Form_Run_Volumes"] = "卷挂载(一行一条)",
        ["Form_Run_Env"] = "环境变量(一行一条 KEY=value)",
        ["Form_Run_Network"] = "网络",
        ["Form_Run_Restart"] = "重启策略",
        ["Form_Run_Detach"] = "后台运行 (-d)",
        ["Form_Run_Rm"] = "退出即删 (--rm)",
        ["Form_Run_Extra"] = "额外参数",
        ["Form_Run_ExtraHint"] = "原样接进命令行 —— 与在终端里手敲同权。",
        ["Form_Run_Command"] = "覆盖启动命令",
        ["Form_Rename_Title"] = "重命名 {0}",
        ["Form_Rename_Name"] = "新名字",
        ["Form_Tag_Title"] = "给 {0} 打标签",
        ["Form_Tag_Target"] = "新引用",
        ["Form_Volume_Title"] = "新建卷",
        ["Form_Volume_Name"] = "名称",
        ["Form_Volume_Driver"] = "驱动",
        ["Form_Volume_Options"] = "驱动选项(一行一条 key=value)",
        ["Form_Volume_Labels"] = "标签(一行一条 key=value)",
        ["Form_Network_Title"] = "新建网络",
        ["Form_Network_Name"] = "名称",
        ["Form_Network_Driver"] = "驱动",
        ["Form_Network_Subnet"] = "子网",
        ["Form_Network_Gateway"] = "网关",
        ["Form_Network_Internal"] = "内部网络(不通外网)",
        ["Form_Network_IPv6"] = "启用 IPv6",
        ["Form_Connect_Title"] = "把容器接进 {0}",
        ["Form_Connect_Container"] = "容器",
        ["Form_Connect_Alias"] = "网络别名",
        ["Form_Disconnect_Title"] = "把容器从 {0} 摘掉",
        ["Form_Policy_Title"] = "重启策略",
        ["Form_Policy_Value"] = "策略",
        ["Form_Exec_Title"] = "进入 {0}",
        ["Form_Exec_Shell"] = "Shell",
        ["Form_Exec_User"] = "用户",
        ["Form_Exec_Workdir"] = "工作目录",
        ["Form_ComposeFile_Title"] = "打开 compose 文件",
        ["Form_ComposeFile_Path"] = "远端路径",
        ["Form_ComposeFile_Project"] = "项目名",
        ["Form_ComposeFile_ProjectHint"] = "留空即让 compose 按目录名推导。",

        ["Confirm_Type"] = "键入 {0} 以确认",
        ["Confirm_RemoveContainers"] = "删除 {0} 个容器?",
        ["Confirm_RemoveContainersBody"] = "容器与它的可写层一起没了。具名卷会留下;匿名卷只有勾了「连匿名卷」才删。",
        ["Confirm_RemoveContainersVolumes"] = "连匿名卷一起删 (-v)",
        ["Confirm_Kill"] = "强杀 {0} 个容器?",
        ["Confirm_KillBody"] = "SIGKILL —— 进程没有机会刷缓冲、关连接。除非它已经卡死,否则该用「停止」。",
        ["Confirm_RemoveImages"] = "删除 {0} 个镜像?",
        ["Confirm_RemoveImagesBody"] = "别处没缓存的话,下次就得重新拉一遍。",
        ["Confirm_RemoveVolumes"] = "删除 {0} 个卷?",
        ["Confirm_RemoveVolumesBody"] = "卷里的数据一并删除。没有撤销,也没有回收站。",
        ["Confirm_RemoveNetworks"] = "删除 {0} 张网络?",
        ["Confirm_RemoveNetworksBody"] = "还挂在上面的容器会失去这张网。",
        ["Confirm_ComposeDown"] = "销毁 {0}?",
        ["Confirm_ComposeDownBody"] = "停掉并删除这个项目的容器与网络。",
        ["Confirm_ComposeDownVolumes"] = "连项目的卷一起删 (-v)",
        ["Confirm_Prune"] = "回收空间:{0}?",
        ["Confirm_PruneBody"] = "该类别下一切未使用的东西立即删除。",
        ["Confirm_PruneVolumesBody"] = "未使用的卷会被删掉 —— 包括你可能还要的数据。这是唯一一档会丢数据的回收。",
        ["Confirm_SaveComposeFile"] = "覆盖 {0}?",
        ["Confirm_SaveComposeFileBody"] = "远端文件会被编辑器里的内容整个替换。没进版本库的话,先备份。",

        ["Status_Ready"] = "就绪。",
        ["Status_Working"] = "{0}…",
        ["Status_Refreshed"] = "已于 {0} 刷新。",
        ["Status_Done"] = "{0}:完成。",
        ["Status_Failed"] = "{0} 失败:{1}",
        ["Status_Batch"] = "{0}:成功 {1}、失败 {2} —— {3}",
        ["Status_BatchOk"] = "{0}:{1} 项完成。",
        ["Status_NoSelection"] = "先选中至少一行。",
        ["Status_NoSession"] = "先选一条已连接的 SSH 会话。",
        ["Status_Copied"] = "已复制。",
        ["Status_TerminalSent"] = "已送进终端标签。",
        ["Status_TerminalDenied"] = "你拒绝了写入终端,什么都没发出去。",
        ["Status_Saved"] = "已保存 {0}。",
        ["Status_FileRead"] = "已读取 {0}。",
        ["Status_Cancelled"] = "已取消。",
        ["Status_EngineUnavailable"] = "这条会话上的 docker 还不可用。"
    };
}
